swagger: "2.0"
info:
  version: "1.0.0"
  title: "Farm API"
host: farm-api.herokuapp.com
basePath: "/api"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /farms:
    get:
      summary: "List of farms"
      parameters:
        - name: state
          in: query
          description: "Which state to filter farms by"
          required: true
          type: string
      responses:
        "200":
          description: "An array of farm objects"
  /locations:
    get:
      summary: "List of locations (farms & markets)"
      parameters:
        - name: lat
          in: query
          description: "latitude"
          type: number
          required: true
        - name: lon
          in: query
          description: "longitude"
          type: number
          required: true
        - name: distance
          in: query
          description: "search radius in miles"
          type: number
      responses:
        "200":
          description: "An array of location objects and a count"
          schema:
            type: object
            properties:
              count:
                type: number
              rows:
                type: array
                items:
                  $ref: "#/definitions/location"

definitions:
  contact:
    properties:
      website:
        type: string
      facebook:
        type: string
      twitter:
        type: string
      youtube:
        type: string
      instagram:
        type: string

  address:
    properties:
      street:
        type: string
      city:
        type: string
      county:
        type: string
      state:
        type: string
      zip:
        type: string

  payment:
    properties:
      hasCredit: boolean
    hasWIC:
      hasCredit: boolean
    hasWICcash:
      hasCredit: boolean
    hasSFMNP:
      hasCredit: boolean
    hasSNAP:
      hasCredit: boolean

  product:
    properties:
      _id:
        type: string
      name:
        type: string

  season:
    properties:
      _id:
        type: string
      day:
        type: string
      time:
        type: string
      notes:
        type: string
      products:
        type: array
        items: "#/definitions/product"

  facility:
    properties:
      _id:
        type: string
      name:
        type: string

  activity:
    properties:
      _id:
        type: string
      name:
        type: string

  location:
    properties:
      _id:
        type: string
      name:
        type: string
      description:
        type: string
      type:
        type: string
      contact:
        $ref: "#/definitions/contact"
      address:
        $ref: "#/definitions/address"
      geo:
        type: array
        items:
          type: number
      payment:
        $ref: "#/definitions/payment"
      products:
        type: array
        items: "#/definitions/product"
      stateID:
        type: string
      seasons:
        type: array
        items: "#/definitions/season"
      facilities:
        type: array
        items: "#/definitions/facility"
      activities:
        type: array
        items: "#/definitions/activity"
